### ISSUE TITLE
Add Tests

### ISSUE THREAD

**Issue by pathawks** [jekyll/jekyll-commonmark#14]
Obviously we need to add some tests to this plugin.

It hasn't been a priority in the past, because this Gem is just a very thin wrapper around [commonmarker](https://github.com/gjtorikian/commonmarker), which _does_ have it's own test suite.

We should decide what we need to test. I suppose we could use Jekyll's [redcarpet](https://github.com/jekyll/jekyll/blob/73419cb374be1b8f45818a23116cf71db93549ce/test/test_redcarpet.rb) and [rdiscount](https://github.com/jekyll/jekyll/blob/73419cb374be1b8f45818a23116cf71db93549ce/test/test_rdiscount.rb) tests as a starting point.

**Comment by ashmaroli** [comment]
Do you plan to switch to Minitest and Shoulda or port those tests to Rspec?

**Comment by pathawks** [comment]
We will use Rspec for tests, just like our other plugins :+1:
