### ISSUE TITLE
Release a new version

### ISSUE THREAD

**Issue by tbodt** [jekyll/jekyll-commonmark#20]
Version 1.1.0 was released on 6/17/2017, and support for render options was added after that. I'd like to be able to use those.

**Comment by DirtyF** [comment]
@pathawks I'm fine with releasing a 1.1.0 version if you're too busy.

**Comment by pathawks** [comment]
It looks like support for render options is the _only_ user facing change that has been made, but you're right that we should release `1.1.0`.

@DirtyF If you'd be so kind, that would be awesome. Otherwise, I can cut a :gem: in a few hours.

**Comment by DirtyF** [comment]
@tbodt it's out! https://github.com/jekyll/jekyll-commonmark/releases/tag/v1.2.0

**Comment by tbodt** [comment]
@DirtyF thanks for doing this so quickly!
