### ISSUE TITLE
Plugin to Make jekyll-commonmark Extensible in Ruby

### ISSUE THREAD

**Issue by pyrmont** [jekyll/jekyll-commonmark#31]
I've developed a plug-in called [jekyll-commonmark-pluggable](https://github.com/pyrmont/jekyll-commonmark-pluggable) that provides a mechanism to hook into the CommonMark rendering pipeline with code written in Ruby. The mechanism itself is hacky (I monkey patch the `#convert` method) but it does at least make it easy to write encapsulated plugins.

With jekyll-commonmark-pluggable, it's relatively straightforward to make adjustments to the markup generated by CommonMarker. I have two plugins running on my Jekyll installation which show what it can do. One plugin [changes the HTML for code blocks](https://github.com/pyrmont/articles/blob/master/_plugins/commonmarker-syntax-highlighter.rb) while the other plugin (in conjunction with some CSS) [ensures that a footnote doesn't break across lines](https://github.com/pyrmont/articles/blob/master/_plugins/commonmarker-footnote-fixer.rb).

I'm not sure if this is the best place to announce this but I thought it might be helpful to other users who file issues here requesting changes be made to the way rendering works.

**Comment by ashmaroli** [comment]
@pyrmont The Jekyll Organisation does not entertain nor encourage tickets that are not bug-reports.
The idea is good nevertheless. But a plugin for a plugin for a plugin is well, :man_shrugging: 

We have a forum at https://talk.jekyllrb.com/ that allows you to connect with the community.

**Comment by pyrmont** [comment]
@ashmaroli Understood! :) I'll let people know about it on the forum!
